### ISSUE TITLE
Upgrade pyyaml due to security vulnerability

### ISSUE THREAD

**Issue by ConstantineLignos** [isi-vista/vistautils#34]
Hopefully this link works: https://github.com/isi-vista/vistautils/network/alert/requirements.txt/pyyaml/open

@rgabbard can you take a look/delegate as needed? I assume this should be trivial, but I'm not sure how much we'd need to test and whether new versions introduce any problems for us.

**Comment by rgabbard** [comment]
Looking at the changelog for `pyyaml`, I don't think any of the changes from 3.X -> 4.X should cause us a problem and we have at least some tests for loading from YAML, so I think we can just make this change and trust the tests.  @nicomitchell , can you take care of this as one of your "Ryan-time" tasks?

**Comment by nicomitchell** [comment]
The link is broken for me, can you elaborate?

**Comment by ConstantineLignos** [comment]
Sorry, basically it links to a page that says there's a security issue with the version of pyyaml in our requirements.txt, and the following:
> Remediation
> Upgrade pyyaml to version 4.2b1 or later. For example:
> pyyaml>=4.2b1

We might as well update to 4.2b4. There does not appear to be a stable release with this fix.

**Comment by ConstantineLignos** [comment]
Closed by #35.
