### ISSUE TITLE
Add convenience type-checked converters

### ISSUE THREAD

**Issue by ConstantineLignos** [isi-vista/vistautils#36]
ImmutableCollections is good at type checking the top type for containers, but has performance implications that users may need to avoid. I'd like to add convenience methods for the case where you want to convert an iterable to a collection (immutable or not) while checking type. The common use case would be as an argument to `converter` with `attr.attrib`, but they could be useful elsewhere. For example:

```
@attrs
class Foo:
    contents = attrib(converter=tuple_checking_type(str))
```

Things to implement: `tuple_checking_type`, `(frozen)dict_checking_type` and `(frozen)set_checking_type`.

**Comment by rgabbard** [comment]
I think this is now taken care of by `attrs`'s `deep_iterable`.
