### ISSUE TITLE
Indexing for HasSpan objects

### ISSUE THREAD

**Issue by rgabbard** [isi-vista/vistautils#42]
In NLP, we very frequently need to do fast indexed lookups of `HasSpan` objects.  We should build a single index object for this and reuse it instead of repeatedly reinventing the wheel.

I would propose something like:

```
T = TypeVar('T', bound=HasSpan)

class HasSpanIndex(Generic[T], ABC):
    def lookup_by_exact_match(self, span: Span) -> ImmutableSet[T]:
    def lookup_overlapping(self, span: Span) -> ImmutableSet[T]:
    def lookup_contained(self, span: Span) -> ImmutableSet[T]:
    def lookup_containing(self, span: Span) -> ImmutableSet[T]:
         
    @staticmethod
    def index(items: Iterable[T]) -> HasSpanIndex[T]:
    @staticmethod
    def index_disjoint(items: Iterable[T]) -> DisjointHasSpanIndex[T]:

class DisjointHasSpanIndex(HasSpanIndex[T], ABC):
     def get_exactly_matching(self, span: Span) -> Optional[T]:
    def get_containing(self, span: Span) -> Optional[T]:
```

**Comment by berquist** [comment]
Can you explain the different between `lookup_contained` and `lookup_containing`?

I've defined `lookup_containing` as "find the spans containing the given span", `key_span.contains(given_span) for key_span in span_to_item_map`. Is `lookup_contained` "find all the spans contained in the given span", `given_span.contains(key_span) for key span in span_to_item_map`?

**Comment by rgabbard** [comment]
@berquist : Exactly right.

**Comment by rgabbard** [comment]
Note for `DisjointHasSpanIndex` I think this can all be straightforwardly implemented with `ImmutableRangeMap`; you have split the non-disjoint case to another issue.

Also note that due to https://github.com/isi-vista/vistautils/issues/37 you probably want to represent spans as closed intervals and not half-open intervals.
